services:
  study-traker:
    image: 100.87.250.21:5000/study-traker:latest
    container_name: study-traker
    ports:
      - "8082:8082"
    environment:
      - Secret_Token_Key=${Secret_Token_Key}
    volumes:
      - ../data:/app/data
    networks:
      - dify_net
    restart: unless-stopped
networks:
  dify_net:
    external: true
    name: docker_default